### ISSUE TITLE
LIKE MySQL operator

### ISSUE THREAD

**Issue by theleemon** [moderntribe/advanced-post-manager#15]
The __construct() function in the /lib/tribe-filters.class.php file contains the following code:

    $this->query_options_map = array( // turn into SQL comparison operators
        'is' => '=',
        'not' => '!=',
        'gt' => '>',
        'lt' => '<',
        'gte' => '>=',
        'lte' => '<=',
        'like' => __('LIKE','tribe-apm')
    );

According to the comment, it's a SQL comparison operators conversion array. My question is, is it right to make the LIKE operator translatable?

**Comment by borkweb** [comment]
Ha! Thanks for the catch on that one :D This has been resolved in https://github.com/moderntribe/advanced-post-manager/pull/16
