### ISSUE TITLE
Dependency on select2?

### ISSUE THREAD

**Issue by pablomargareto** [moderntribe/advanced-post-manager#23]
Hello guys,

Congrats for the plugin! It's great! :)

I have been using it with a site that has TEC installed on it and everything working fine.

However, I have installed this plugin for a site without TEC installed and it seems that you need the plugin of "select2"... which is not included into this plugin.

I have added it by myself but the filter selector does not work well. Am I missing something? Perhaps you have your own version of select2?

Thanks and regards,

Pablo

**Comment by zbtirrell** [comment]
Thanks for the bug report, we really appreciate it. We don't monitor GitHub Issues and had forgotten to disable it here. I ticketed this in our internal tracking system and I'm going to close out this issue. 

In the future, we'd be happy to take bug reports in the WordPress.org support forums - https://wordpress.org/support/plugin/advanced-post-manager
